//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitAssignment
    {
        public int SysId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> AssesmentId { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Assesment Assesment { get; set; }
    }
}
