//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teach
    {
        public int SysId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> SectionId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual Section Section { get; set; }
        public virtual Year Year { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
